package cn.yeslab.platform.identity.model;

public enum Permission {
    SYSTEM_ADMIN,
    MEMBER_MANAGE,
    RECRUITMENT_MANAGE,
    TAG_MANAGE,
    QUIZ_MANAGE,
    POINTS_MANAGE,
    PROJECT_MANAGE,
    ACHIEVEMENT_MANAGE,
    CONTENT_MANAGE,
    PROFILE_SELF_EDIT,
    QUIZ_PARTICIPATE,
    QUESTION_WRITE,
    RECRUITMENT_SELF_EDIT,
    RECRUITMENT_SELF_VIEW
}
